// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1e9BzTtoSNMDqKgLkOkMNr8sGgJh1z8M',
    appId: '1:799091892716:web:cfe60deb72574f857760c9',
    messagingSenderId: '799091892716',
    projectId: 'expensetracker-66e6a',
    authDomain: 'expensetracker-66e6a.firebaseapp.com',
    databaseURL: 'https://expensetracker-66e6a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'expensetracker-66e6a.appspot.com',
    measurementId: 'G-YLJK0FEB7R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCj-3c1_7NExbmaTb_I3aFLI5JTj0AtSQ',
    appId: '1:799091892716:android:62b1ab22313250627760c9',
    messagingSenderId: '799091892716',
    projectId: 'expensetracker-66e6a',
    databaseURL: 'https://expensetracker-66e6a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'expensetracker-66e6a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzE2Zcrnv2BQoVV9iP0GX-OKqgcjsg0Bo',
    appId: '1:799091892716:ios:1538437b01768b9d7760c9',
    messagingSenderId: '799091892716',
    projectId: 'expensetracker-66e6a',
    databaseURL: 'https://expensetracker-66e6a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'expensetracker-66e6a.appspot.com',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzE2Zcrnv2BQoVV9iP0GX-OKqgcjsg0Bo',
    appId: '1:799091892716:ios:f6eb3eb1c1bd437d7760c9',
    messagingSenderId: '799091892716',
    projectId: 'expensetracker-66e6a',
    databaseURL: 'https://expensetracker-66e6a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'expensetracker-66e6a.appspot.com',
    iosBundleId: 'com.example.expenseTracker.RunnerTests',
  );
}
