// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqDZ7hHPEyoJyJFOHlC_vm3UIrXpkCTks',
    appId: '1:671994291567:web:40629cb7aa542128efb49a',
    messagingSenderId: '671994291567',
    projectId: 'expensetracker-ba9a1',
    authDomain: 'expensetracker-ba9a1.firebaseapp.com',
    storageBucket: 'expensetracker-ba9a1.appspot.com',
    measurementId: 'G-93MVPGQQCF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABBLOPeUvUjZTHJcJ0omGDU0gHyuLuA8M',
    appId: '1:671994291567:android:3fa0345f01cd232aefb49a',
    messagingSenderId: '671994291567',
    projectId: 'expensetracker-ba9a1',
    storageBucket: 'expensetracker-ba9a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0fgaNd3NXZS3Dl5bGiMQpc1QjASP722c',
    appId: '1:671994291567:ios:4538486f13bfc897efb49a',
    messagingSenderId: '671994291567',
    projectId: 'expensetracker-ba9a1',
    storageBucket: 'expensetracker-ba9a1.appspot.com',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0fgaNd3NXZS3Dl5bGiMQpc1QjASP722c',
    appId: '1:671994291567:ios:4538486f13bfc897efb49a',
    messagingSenderId: '671994291567',
    projectId: 'expensetracker-ba9a1',
    storageBucket: 'expensetracker-ba9a1.appspot.com',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqDZ7hHPEyoJyJFOHlC_vm3UIrXpkCTks',
    appId: '1:671994291567:web:0a0563580412762defb49a',
    messagingSenderId: '671994291567',
    projectId: 'expensetracker-ba9a1',
    authDomain: 'expensetracker-ba9a1.firebaseapp.com',
    storageBucket: 'expensetracker-ba9a1.appspot.com',
    measurementId: 'G-5VVWT6MJWW',
  );
}
